"""
config.py
=========
Central configuration file for the AI Tuberculosis Detection and Severity Assessment System.

This file stores all key settings including paths, model parameters, severity thresholds,
and reinforcement learning hyperparameters. Adjust these values to customize the system
for your dataset and hardware.

Author: AI TB Detection Team
Date: 2026
License: Research/Educational Use Only
"""

import os

# ─────────────────────────────────────────────────────────────────────────────
# PROJECT PATHS
# ─────────────────────────────────────────────────────────────────────────────

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Data directories
DATA_DIR        = os.path.join(BASE_DIR, "data")
TRAIN_DIR       = os.path.join(DATA_DIR, "train")
VAL_DIR         = os.path.join(DATA_DIR, "val")
TEST_DIR        = os.path.join(DATA_DIR, "test")
NEW_DATA_DIR    = os.path.join(BASE_DIR, "new_data")   # Drop new labeled images here

# Model storage
MODELS_DIR      = os.path.join(BASE_DIR, "models")
MODEL_WEIGHTS   = os.path.join(MODELS_DIR, "tb_yolo.pt")          # Base model
UPDATED_WEIGHTS = os.path.join(MODELS_DIR, "tb_yolo_updated.pt")  # After fine-tuning

# Output / report directories
OUTPUT_DIR      = os.path.join(BASE_DIR, "output")
REPORTS_DIR     = os.path.join(BASE_DIR, "reports")

# Reinforcement learning feedback log
RL_FEEDBACK_FILE = os.path.join(DATA_DIR, "rl_feedback.json")

# Evaluation report output
EVAL_REPORT_FILE = os.path.join(REPORTS_DIR, "evaluation.json")

# ─────────────────────────────────────────────────────────────────────────────
# YOLO MODEL SETTINGS
# ─────────────────────────────────────────────────────────────────────────────

# YOLO model variant: 'yolov8n', 'yolov8s', 'yolov8m', 'yolov8l', 'yolov8x'
# Start with 'yolov8n' (nano) for fast experimentation, 'yolov8m' for better accuracy
YOLO_MODEL_SIZE = "yolov8n"

# Class names in the dataset (must match dataset annotation labels)
CLASS_NAMES = ["normal", "tuberculosis"]

# Confidence threshold: detections below this score are discarded
CONFIDENCE_THRESHOLD = 0.25

# IoU threshold for NMS (Non-Maximum Suppression) — removes overlapping boxes
IOU_THRESHOLD = 0.45

# Image input size for YOLO (must match training resolution)
IMAGE_SIZE = 640

# ─────────────────────────────────────────────────────────────────────────────
# TRAINING SETTINGS
# ─────────────────────────────────────────────────────────────────────────────

TRAIN_EPOCHS     = 100    # Number of training epochs
TRAIN_BATCH_SIZE = 16     # Images per batch (reduce if GPU OOM)
TRAIN_LR         = 0.01   # Initial learning rate
TRAIN_WORKERS    = 4      # DataLoader worker threads
TRAIN_PATIENCE   = 20     # Early stopping patience (epochs)

# Dataset yaml path (generated by dataset_loader or Roboflow download)
DATASET_YAML = os.path.join(DATA_DIR, "dataset.yaml")

# ─────────────────────────────────────────────────────────────────────────────
# SEVERITY ESTIMATION THRESHOLDS
# ─────────────────────────────────────────────────────────────────────────────
# These thresholds define severity levels based on infected lung area percentage.
# They are dynamically updated by the Reinforcement Learning module over time.

SEVERITY_THRESHOLDS = {
    "mild_max":     10.0,   # Lesion area < 10%  → Mild
    "moderate_max": 30.0,   # 10%–30%            → Moderate
    # >30% → Severe
}

# Clinical risk score weights (used in weighted scoring formula)
RISK_WEIGHT_AREA       = 0.5   # Weight for infected area percentage
RISK_WEIGHT_COUNT      = 0.3   # Weight for lesion count (normalized)
RISK_WEIGHT_CONFIDENCE = 0.2   # Weight for average detection confidence

# Maximum lesion count used for normalization purposes
MAX_LESION_COUNT_NORM  = 20

# ─────────────────────────────────────────────────────────────────────────────
# REINFORCEMENT LEARNING SETTINGS
# ─────────────────────────────────────────────────────────────────────────────

# Reward values for RL feedback
RL_REWARD_CORRECT = 1.0    # Model prediction exactly matched expert
RL_REWARD_CLOSE   = 0.5    # Model was one level off (e.g., Mild vs Moderate)
RL_REWARD_WRONG   = -1.0   # Model was significantly wrong

# Learning rate for Q-learning style threshold update
RL_LEARNING_RATE  = 0.05

# ─────────────────────────────────────────────────────────────────────────────
# FINE-TUNING SETTINGS
# ─────────────────────────────────────────────────────────────────────────────

FINETUNE_EPOCHS     = 20     # Epochs when fine-tuning on new data
FINETUNE_BATCH_SIZE = 8      # Smaller batch for fine-tuning
FINETUNE_LR         = 0.001  # Lower LR to avoid catastrophic forgetting
FREEZE_LAYERS       = 10     # Number of backbone layers to freeze during fine-tuning

# ─────────────────────────────────────────────────────────────────────────────
# MISCELLANEOUS
# ─────────────────────────────────────────────────────────────────────────────

RANDOM_SEED = 42    # For reproducibility

# Approximate lung region as fraction of image (used for area normalization)
# A real system would use a lung segmentation model; this is a simplified approximation
LUNG_AREA_FRACTION = 0.40  # Assume lungs occupy ~40% of a frontal chest X-ray
