"""
report_generator.py
===================
Module 5: Medical Report Generation for TB Detection Results.

This module combines:
  - YOLO detection results (from detect_tb.py)
  - Severity assessment (from severity_calculator.py)
into a structured JSON medical report.

It also produces a visual output image with:
  - Bounding boxes drawn on the chest X-ray
  - Severity overlay text

Medical Disclaimer:
  This report is generated by an AI system for RESEARCH PURPOSES ONLY.
  It must NOT be used as a substitute for professional medical diagnosis.
  Always consult a qualified physician for TB diagnosis and treatment.

Author: AI TB Detection Team
License: Research/Educational Use Only
"""

import os
import sys
import json
from datetime import datetime

import cv2
import numpy as np

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from severity.severity_calculator import SeverityCalculator


# ─────────────────────────────────────────────────────────────────────────────
# REPORT GENERATOR CLASS
# ─────────────────────────────────────────────────────────────────────────────

class ReportGenerator:
    """
    Generates structured medical reports from TB detection and severity results.

    Attributes:
        calculator (SeverityCalculator): Instance used for severity and recommendations.
    """

    def __init__(self):
        """Initialize the report generator with a severity calculator."""
        self.calculator = SeverityCalculator()

    # ─────────────────────────────────────────────────────────────────────────
    def generate_report(self, detection_result: dict) -> dict:
        """
        Generate a structured JSON medical report from detection results.

        Args:
            detection_result (dict): Output from TBDetector.detect()

        Returns:
            dict: Full medical report with the following keys:
              - image_name
              - tb_detected
              - lesion_count
              - infected_area_percent
              - severity_level
              - confidence_average
              - clinical_risk_score
              - recommendation
              - timestamp
              - disclaimer
        """
        # Extract core metrics from the detection result
        image_name   = detection_result.get("image_name", "unknown")
        tb_detected  = detection_result.get("tb_detected", False)
        lesion_count = detection_result.get("lesion_count", 0)
        area_pct     = detection_result.get("infected_area_percent", 0.0)
        conf_avg     = detection_result.get("confidence_avg", 0.0)

        # Calculate severity (if no TB detected, severity is 'None')
        if tb_detected:
            severity_result = self.calculator.calculate(
                infected_area_percent = area_pct,
                lesion_count          = lesion_count,
                confidence_avg        = conf_avg,
            )
            severity_level = severity_result["severity_level"]
            risk_score     = severity_result["risk_score"]
            recommendation = self.calculator.get_recommendation(severity_level)
        else:
            severity_level = "None"
            risk_score     = 0
            recommendation = ("No TB lesions detected. "
                              "Routine health monitoring recommended. "
                              "Consult a physician if symptoms persist.")

        # Build the full report dictionary
        report = {
            "image_name"            : image_name,
            "timestamp"             : datetime.now().isoformat(),
            "tb_detected"           : tb_detected,
            "lesion_count"          : lesion_count,
            "infected_area_percent" : round(area_pct, 2),
            "severity_level"        : severity_level,
            "confidence_average"    : round(conf_avg, 4),
            "clinical_risk_score"   : risk_score,
            "recommendation"        : recommendation,
            "disclaimer"            : (
                "⚠️  RESEARCH USE ONLY — This AI-generated report is NOT a clinical "
                "diagnosis. Consult a qualified medical professional for any health concerns."
            ),
        }

        return report

    # ─────────────────────────────────────────────────────────────────────────
    def save_report_json(self, report: dict,
                          output_path: str = None) -> str:
        """
        Save the medical report as a formatted JSON file.

        Args:
            report      (dict): Report dictionary from generate_report().
            output_path (str):  Path to save JSON. Defaults to reports/<image_name>.json

        Returns:
            str: Absolute path to the saved JSON file.
        """
        if output_path is None:
            os.makedirs(config.REPORTS_DIR, exist_ok=True)
            base_name   = os.path.splitext(report.get("image_name", "report"))[0]
            output_path = os.path.join(config.REPORTS_DIR, f"{base_name}_report.json")

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

        print(f"[INFO] Report saved to: {output_path}")
        return output_path

    # ─────────────────────────────────────────────────────────────────────────
    def generate_visual_output(self,
                                image_path: str,
                                detection_result: dict,
                                report: dict,
                                output_path: str = None) -> str:
        """
        Draw detection results on the X-ray image and save as annotated output.

        Draws:
          - Colored bounding boxes (color varies by confidence)
          - Confidence score labels
          - Severity level and risk score overlay in top-left corner
          - TB DETECTED / NO TB banner

        Args:
            image_path       (str):  Path to original X-ray image.
            detection_result (dict): Output from TBDetector.detect().
            report           (dict): Output from generate_report().
            output_path      (str):  Path to save annotated image.

        Returns:
            str: Path to the saved annotated image.
        """
        # Load original image
        image = cv2.imread(image_path)
        if image is None:
            print(f"[ERROR] Cannot load image for visualization: {image_path}")
            return None

        h, w = image.shape[:2]

        # ── Color scheme based on severity ────────────────────────────────────
        severity_colors = {
            "None"     : (0, 200, 0),     # Green — no TB
            "Mild"     : (0, 200, 255),   # Yellow — mild
            "Moderate" : (0, 140, 255),   # Orange — moderate
            "Severe"   : (0, 0, 255),     # Red — severe
        }
        severity_level = report.get("severity_level", "None")
        box_color      = severity_colors.get(severity_level, (0, 200, 0))

        # ── Draw bounding boxes for each detected lesion ───────────────────────
        for i, det in enumerate(detection_result.get("detections", []), 1):
            x1, y1, x2, y2 = det["box_xyxy"]
            conf            = det["confidence"]

            # Confidence-modulated alpha for box thickness
            thickness = max(1, int(conf * 4))
            cv2.rectangle(image, (x1, y1), (x2, y2), box_color, thickness)

            # Label: lesion number + confidence
            label = f"TB#{i} {conf:.2f}"
            (lw, lh), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
            cv2.rectangle(image, (x1, y1 - lh - 6), (x1 + lw + 4, y1), box_color, -1)
            cv2.putText(image, label, (x1 + 2, y1 - 4),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)

        # ── Top overlay banner ─────────────────────────────────────────────────
        banner_h = 70
        overlay  = image.copy()
        cv2.rectangle(overlay, (0, 0), (w, banner_h), (20, 20, 20), -1)
        cv2.addWeighted(overlay, 0.75, image, 0.25, 0, image)

        # Detection status text
        status_text = "TB DETECTED ⚠" if report["tb_detected"] else "NO TB DETECTED ✓"
        cv2.putText(image, status_text, (10, 22),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7,
                    (0, 80, 255) if report["tb_detected"] else (0, 200, 80), 2)

        # Severity & risk score
        info_text = (f"Severity: {severity_level}  |  "
                     f"Risk: {report['clinical_risk_score']}/100  |  "
                     f"Lesions: {report['lesion_count']}  |  "
                     f"Area: {report['infected_area_percent']:.1f}%")
        cv2.putText(image, info_text, (10, 50),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (200, 200, 200), 1)

        # ── Save annotated image ───────────────────────────────────────────────
        if output_path is None:
            os.makedirs(config.OUTPUT_DIR, exist_ok=True)
            base_name   = os.path.splitext(report.get("image_name", "xray"))[0]
            output_path = os.path.join(config.OUTPUT_DIR, f"{base_name}_annotated.jpg")

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        cv2.imwrite(output_path, image)
        print(f"[INFO] Annotated image saved to: {output_path}")
        return output_path

    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def print_report(report: dict):
        """Print a formatted medical report to the console."""
        print("\n" + "═" * 60)
        print("  📋  TB MEDICAL REPORT")
        print("═" * 60)
        print(f"  Image       : {report.get('image_name')}")
        print(f"  Timestamp   : {report.get('timestamp')}")
        print(f"  TB Detected : {'YES ⚠️' if report.get('tb_detected') else 'NO ✅'}")
        print(f"  Lesions     : {report.get('lesion_count')}")
        print(f"  Infected %  : {report.get('infected_area_percent')}%")
        print(f"  Severity    : {report.get('severity_level')}")
        print(f"  Avg Conf    : {report.get('confidence_average')}")
        print(f"  Risk Score  : {report.get('clinical_risk_score')} / 100")
        print("─" * 60)
        print(f"  Recommendation:\n  {report.get('recommendation')}")
        print("─" * 60)
        print(f"  {report.get('disclaimer')}")
        print("═" * 60)


# ─────────────────────────────────────────────────────────────────────────────
# STANDALONE DEMO
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # Simulate a detection result for demonstration
    mock_detection = {
        "image_name"            : "patient_xray_001.jpg",
        "tb_detected"           : True,
        "lesion_count"          : 5,
        "infected_area_percent" : 22.5,
        "confidence_avg"        : 0.84,
        "detections"            : [
            {"confidence": 0.91, "box_xyxy": [100, 150, 200, 250], "area_pixels": 10000},
            {"confidence": 0.78, "box_xyxy": [300, 200, 380, 290], "area_pixels": 7200},
        ],
    }

    generator = ReportGenerator()
    report    = generator.generate_report(mock_detection)
    generator.print_report(report)

    saved = generator.save_report_json(report)
    print(f"\nReport JSON: {saved}")
